apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: db-ns
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: mensagensdb
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: app-ns
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres

